### ISSUE TITLE
Use tsconfig.json

### ISSUE THREAD

**Issue by wind-rider** [pushrocks/npmts#8]
Is there an option to use tsconfig.json?

I see that npmts uses its own internal tsconfig.json which breaks my code.
- I want to include my typings in tsconfig.json instead of using /// \<reference path="./typings/main.d.ts" />
- I want to use ES6 but npmts hardcodes it to ES5

**Comment by philkunz** [comment]
Hi, I'll take a look tomorrow and report back here.

**Comment by wind-rider** [comment]
Great, thank you for your quick feedback

**Comment by philkunz** [comment]
I added this feature to the 6.x.x milestone. You can watch this issue and get notified when it is implemented. It'll probably integrated as option in 5.x.x before 6.x.x as I don't see a breaking change.

**Comment by philkunz** [comment]
So where should it look for tsconfig.json? at the root `./` or at `./ts/`  ?
I think standard would be the root, but it should check at ./ts/ first to keep the TypeScript in one directory.

**Comment by wind-rider** [comment]
both seem good, I'm new to TypeScript and I see multiple styles..

The approach you proposed sounds the most robust.

**Comment by philkunz** [comment]
So I looked a little bit further into the issue. I will support compiler options in npmts.json, which will allow you to control TypeScript (ES6,ES5, module system...).
However I will not support tsconfig.json as this kind of negates the purpose of npmts. You can use tsc directly for this.

I'm currently working on the implementation of compiler options in npmts.json.

**Comment by philkunz** [comment]
version 5.1.0 and above now supports tsOptions in npmts.json.
